var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/book/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ce93112b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_164c3abe._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b542c83._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2c29245f._.js")
R.c("server/chunks/ssr/_d4a6990b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_book_page_actions_85d30f8f.js")
R.m(84069)
module.exports=R.m(84069).exports
