var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__4ac33c15._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/_8a664c6b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6b542c83._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2c29245f._.js")
R.c("server/chunks/ssr/_d4a6990b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_login_page_actions_a6f7a28f.js")
R.m(9239)
module.exports=R.m(9239).exports
