var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__be75060d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b9a0874._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_e8b0ce4e.js")
R.c("server/chunks/ssr/[root-of-the-server]__fa092045._.js")
R.c("server/chunks/ssr/[root-of-the-server]__e17d8479._.js")
R.c("server/chunks/ssr/node_modules_next_dist_77ec7569._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2c29245f._.js")
R.c("server/chunks/ssr/_d4a6990b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app__not-found_page_actions_3df07a96.js")
R.m(87504)
module.exports=R.m(87504).exports
